mapzen/metro-extracts

circle.yml
deploy

deploy to s3

---

pages/metro-extracts.yml

copy for the callout

---

App/__init__.py
circle.yml
test.py

Checking to see whether Heroku review app process works as-advertised.

Switched from "Yo" to "Oi" for testing

---

pages/metro-extracts.yml
src/scripts/metro.js
src/templates/index.mustache.html

top of page and popup call to action

---

pages/metro-extracts.yml
src/scripts/metro.js

removing the popup on download

---

pages/metro-extracts.yml

survey url

---

Makefile
package.json
src/scss/main.scss

- takes files from `src/scss` and spit to `dist/css`

scss set up

---

pages/metro-extracts.yml

closes #29 
@souperneon I'm not sure how we missed this! better late than never :)

updating copy text

---

App/__init__.py
requirements.txt

Updates https://github.com/mapzen/data-pages/pull/35 with a new path, `/wof/{id}.geojson` e.g. https://mapzen-odes-extracts-pr-36.herokuapp.com/wof/85921881.geojson.

Added proxy for WoF spelunker requests by ID

---

App/static/city.html
App/static/index.html

closes #38 
https://mapzen-odes-extracts-pr-39.herokuapp.com/static/index.html
Click on a city name in the existing-extracts-list to open a new page. City page contains:

url with bounding box and pulling it up on the next page

---

App/__init__.py
App/templates/index.html
App/templates/layout.html
App/templates/metro.html
cities.json

Added HTML page for front page and permalink for each metro extracts.

Pythonify cities list

---

App/templates/index.html

reworking "nearby cities"

---

App/templates/index.html

closes #48 
drag handler looks like this now, and the cursor is one of the resizey ones instead of pointer

new drag handler

---

App/oauth.py
App/templates/oauth/error-authenticate.html
App/web.py
requirements.txt

Test authentication here: https://mapzen-odes-extracts-pr-52.herokuapp.com/oauth/hello
Closes #46.
It will ask you to authenticate with Mapzen, and then (after you’re successful) will return you to a page where it knows your name and you can log back out.
This just verifies that the OAuth loop is working. Assigning to @sleepylemur to check my use of Mapzen OAuth loop. I’d also like to borrow [Github’s `state` feature](https://developer.github.com/v3/oauth/#parameters):
> An unguessable random string. It is used to protect against cross-site request forgery attacks.

Connect to Mapzen with OAuth

---

App/templates/index.html

fills in the outline for higher visibility
smarter zoom on bounding box
fixed an error with type to search

tiny upgrades

---

App/oauth.py
App/odes.py
App/templates/odes/extract.html
App/templates/odes/extracts.html
App/templates/odes/index.html
App/web.py

Use ODES API

---

pages/metro-extracts.yml

adding links to the top of the page for frequently requested links

---

App/templates/index.html

Get autocomplete up to speed with the search demo

---

App/templates/index.html
App/templates/metro.html

new metro page design

---

App/templates/index.html

closes #66 
test with africa and using the autocomplete

if name from autocomplete, use place API instead of search

---

App/templates/index.html

populating the form based on requests

---

App/templates/index.html

closes #62 
if the area is larger than 1deg, have some warning copy
if the area is larger than 5deg, refuse a request

first pass at different states. help with copy appreciated

---

App/__init__.py
App/templates/index.html
App/templates/metro.html

closes #64 
If you get to the page from an enclosing link, this info is passed along in the URL and some extra info is provided on the page

metro clip area for encompassing shapes

---

App/__init__.py
App/oauth.py
App/odes.py
App/web.py
requirements.txt
test.py

Added starter tests

---

App/static/css/metro.css
App/templates/metro.html
App/templates/odes/extract.html

user created extract design

---

App/static/css/common.css
App/static/css/extracts.css
App/static/js/extracts.js
App/templates/odes/extracts.html

extracts page design

---

App/__init__.py
App/oauth.py
App/odes.py
App/static/css/common.css
App/static/css/extracts.css
App/static/css/metros.css
App/static/js/metros.js
App/templates/index.html
App/templates/layout.html
App/util.py
test.py

Added navbar and footer to layout.html, now things need to be adjusted to work.
Closes #84.

Added site-fragments for navbar and footer

---

App/templates/oauth/error-authenticate.html
test.py

closes #80 
** to do: messaging about the auth flow **

Design + Copy for Authentication Page

---

App/__init__.py
App/data.py
App/odes.py
App/static/js/metros.js
App/templates/index.html
App/templates/odes/extract.html
App/templates/odes/extracts.html
app.json
circle.yml
create.pgsql
requirements.txt
test.py

Add a database

---

App/static/js/metros.js
circle.yml

fixing scoping issue for redrawing the request bounding box on drag

---

App/__init__.py

Displaying basic information about headers and things

---

App/__init__.py
App/odes.py
App/templates/email-body.html
App/templates/email-body.txt
App/templates/email-subject.txt
App/templates/odes/index.html
App/util.py
test.py

Add ODES emails

---

App/static/js/metro.js
App/static/js/metros.js
App/web.py

Adjusted static URL path

---

App/static/js/metros.js

feedback welcome if this is a good distance to default to
closes #96

default to 20km radius for places returned as points

---

App/static/css/metros.css
App/static/js/metros.js
App/templates/index.html

closes #94 
defaults to WOF for autocomplete, but allows any search

no search results

---

App/odes.py
test.py

Fixed improper re-request for existing ODES extracts

---

App/static/css/metros.css
App/static/js/metros.js
App/templates/index.html
App/templates/metro.html
App/templates/oauth/error-authenticate.html
App/templates/odes/extract.html

better messaging on extract types!

---

App/__init__.py
test.py

@heffergm does this syntax match what you need? https://mapzen-odes-extracts-pr-125.herokuapp.com/cities-extractor.json (give it a minute to deploy)
Closes #124.

Added cities-extractor.json response

---

App/static/js/metro.js
App/static/js/metros.js
App/templates/index.html
App/templates/metro.html

Switched in more resilient WoF GeoJSON URLs on metro and metros pages

---

App/templates/oauth/error-authenticate.html

Removed target="_blank" for auth form

---

App/static/css/metros.css
App/static/js/metros.js
App/templates/index.html

clear button for searches

---

App/templates/email-body.html

moving email CSS styles to inline

---

App/static/css/metros.css
App/static/js/metros.js

closes #115 
* all four corners drag
* inverting the box corners does not throw an error
* messaging changes based on the size of the box (test by searching for Rhode Island, try making it smaller and bigger, the messaging in the box on the right will change)

improve drag handler behavior

---

App/__init__.py
App/oauth.py
App/odes.py
App/static/css/common.css
App/templates/index.html
App/templates/odes/extract.html
App/templates/odes/extracts.html
App/templates/odes/index.html
App/templates/odes/logout-fragment.html

On ODES pages, `user_id` and `user_nickname` template variables determine whether a user is authenticated. @binx handing this over to you for UI.
Closes #114.

Added user information to determine if they are logged in

---

App/static/css/metros.css
App/templates/odes/extract.html

Formatted ODES extract links just like metro extract links

---

App/static/css/common.css
App/static/css/metros.css

making sure everything works cross-browser

---

App/static/css/metros.css
App/static/js/metros.js

closes #141 
@migurski is this acting closer to what you'd expect now? The one thing I'm not 100% sold on is reseting the map when the search is cleared. It feels a little jumpy to me, but I might also just be reacting to new behavior. Thoughts?

selecting place if autocomplete suggestion, and reset map on clear

---

App/data.py
App/odes.py
create.pgsql
test.py

Switched ODES ID from integer to string

---

App/static/css/metros.css
App/static/js/extract.js
App/static/js/extracts.js
App/static/js/metro.js
App/static/js/metros.js
App/templates/index.html
App/templates/odes/extract.html
App/templates/odes/extracts.html

for reference: https://docs.google.com/document/d/1eWuw0pW1ljlSF1_ihWGyY3c8YW7-IR88rGRt6ylCZu8/edit

upgrade messaging to reference personalized extract requests

---

App/odes.py
App/templates/known-unknown.html
App/util.py
test.py

Trigger this by asking for too many extracts too quickly.
Closes #143.

Added HTML error response for when something goes wrong

---

App/templates/index.html
App/templates/oauth/error-authenticate.html
App/templates/odes/extract.html

messaging upgrades for tomorrow morning

---

App/static/js/extract.js
App/templates/odes/extract.html

closes #150 (it was never in there ;) )

extract outline on custom request page

---

App/__init__.py
App/odes.py
App/templates/known-unknown.html
App/templates/unknown-unknown.html
App/util.py

Looks like https://mapzen-odes-extracts-pr-154.herokuapp.com/sample/unknown-unknown

Report unknown errors more gracefully

---

App/static/css/metro.css
App/static/css/metros.css
App/static/js/metros.js
App/templates/email-body.html
App/templates/email-subject.txt
App/templates/index.html
App/templates/layout.html
App/templates/metro.html
App/templates/oauth/error-authenticate.html
App/templates/odes/extract.html
test.py

closes #155 
@migurski is this the correct variable for the email subject header?

messaging upgrades from ekta and rhonda

---

pages/metro-extracts.yml

new alert on existing page to point to new one

---

App/templates/index.html

info alert box on top of index

---

App/static/css/common.css
App/static/css/metro.css
App/static/css/metros.css
App/static/js/metros.js
App/templates/index.html
App/templates/layout.html
App/templates/metro.html
App/templates/odes/extract.html

ekta requests

---

App/__init__.py
App/sample.py
App/templates/email-body.html
App/templates/email-body.txt
App/web.py
test.py

Closes #161.
Preview will be at https://mapzen-odes-extracts-pr-167.herokuapp.com/sample/email-body

Improved date display in emails

---

App/static/js/extract.js
App/static/js/metro.js
App/static/js/metros.js
App/templates/layout.html

putting in mapzenjs

---

App/static/js/metros.js
App/templates/index.html

hella comments and cleanup
closes #175

fresh new comments in code

---

App/templates/index.html

different alert text

---

App/static/js/extract.js
App/static/js/metro.js
App/static/js/metros.js

186 ux upgrades

---

App/static/js/extract.js
App/static/js/metro.js
App/static/js/metros.js

implementing hanbyuls fallbacktile

---

App/static/css/metros.css
App/templates/index.html

trying out a legend

---

App/static/js/extract.js
App/static/js/metro.js
App/static/js/metros.js

no scroll to zoom and better view set

---

App/static/css/metros.css
App/static/js/metros.js
App/templates/index.html

now with dynamic height calculation and throttle on the scroll.

fancy scroll from pos fix to pos abs

---

App/static/js/metros.js

closes #197 
@migurski @souperneon what do you think?
ex. searching for Teanaway

if there are no wof results, hit the regular search api

---

App/static/css/metros.css
App/static/js/metros.js

closes #200 
different stylings at different zoom levels

first pass at map labels on boxes

---

create.pgsql

Added name field to extracts table

---

App/static/css/metros.css
App/static/js/metros.js
App/templates/index.html

closes #199 
@migurski @souperneon RFC

inserting existing extracts in dropdown list

---

App/templates/metro.html
App/templates/odes/extract.html

adding in your extracts link

---

App/static/js/metros.js

updated copy in dropdown menu

---

App/templates/index.html
App/templates/layout.html

closes #215 
also removes alert box on the index

add page title

---

App/static/css/metro.css
App/static/js/extract.js
App/static/js/metro.js
App/templates/odes/extract.html
App/templates/odes/extracts.html

closes #160 
I'm not sure that the download time/status is very useful on this page, but I think I got everything else. @migurski thoughts?

download page reorganization

---

App/templates/index.html

new copy on index

---

App/static/css/metros.css
App/templates/index.html

new copy in the box

---

App/redirect.py
App/web.py
test.py

We need to account for people's existing emailed links or bookmarks.

Do smart -alt redirects

---

pages/metro-extracts-old.yml

Updated with new top text

---

App/templates/index.html

Based on https://github.com/mapzen/data-pages/issues/236#issuecomment-237926431.

Introduced new top text

---

App/data.py
App/odes.py
App/static/css/metro.css
App/templates/odes/extract.html
App/templates/odes/extracts.html

Added "Again" button

---

App/templates/email-body.html
App/templates/index.html
App/templates/metro.html
App/templates/odes/extract.html

switching to new links

---

App/odes.py
App/static/js/metros.js
test.py

closes #243 
@migurski I believe this is sufficient?

not storing wof_id if source is not whosonfirst

---

App/templates/index.html

adding in text

---

App/templates/odes/extracts.html

updated copy on /extracts

---

App/oauth.py

redirect on logout to the metro-extracts page

---

App/templates/index.html
App/templates/metro.html

making your extracts always visible

---

App/static/css/extracts.css
App/templates/odes/extracts.html

following table styleguide rules

---

App/odes.py
test.py

switching out for the new url

---

App/__init__.py
App/oauth.py
App/odes.py
App/static/css/common.css
App/templates/index.html
App/templates/oauth/hello.html
App/templates/odes/extract.html
App/templates/odes/extracts.html
App/templates/odes/logout-fragment.html
test.py

stubbing out the python for user avatars

---

App/odes.py

closes #232
only use first odes api_key instead of looping through them.

dedup custom extract list

---

App/util.py
test.py

Added case for missing upstream files on metro pages

---

circle.yml

Will cause a new build of docs.

Tickling docs Circle CI

---

cities.json

per user request, we're expanding the Lyon, France metro extract.

update Lyon, France extract

---

App/util.py
test.py

- related https://github.com/mapzen/website/issues/1361

fetching navbar.html reflects new style

---

App/templates/layout.html

- new nav expects user id as as parameter

passing user id for nav

---

App/static/css/common.css
App/static/css/metros.css
App/templates/index.html

Do not merge until new styleguide is out.
Precog appears to be broken so can't preview :/

Update to match new styleguide

---

App/static/scene.yaml

Add api key to scene file in preparation for API keys being removed from new stylesheets next week.

Add api key to scene file

---

docs/custom-extracts.md

Updates the custom extract documentation to consider sign in through email. Also some minor style changes (drop-down, contractions, and present tense).
Related to https://github.com/mapzen/documentation/issues/192

WIP: update for account changes and email sign in

---

App/static/js/metros.js
App/static/scene.yaml

Key got disabled because it was tied to an employee account.

Fix broken search with new API keys
